models.py
from flask import current_app


db = current_app.db

class Post(db.Model):
    __tablename__ = 'post'

    _id = db.Column(db.Integer, nullable=False, autoincrement=True, primary_key=True)
    user = db.Column(db.String, nullable=False)
    content = db.Column(db.String(280), nullable=False)
    date = db.Column(db.DateTime, nullable=False)

    def __init__(self, _id, user, content, date):
        self._id = _id
        self.user = user
        self.content = content
        self.date = date


class Comment(db.Model):
    __tablename__ = 'comment'

    _id = db.Column(db.Integer, nullable=False, autoincrement=True, primary_key=True)
    id_post = db.Column(db.Integer, db.ForeignKey('post._id'))
    user = db.Column(db.String, nullable=False)
    content = db.Column(db.String(280), nullable=False)
    date = db.Column(db.DateTime, nullable=False)

    def __init__(self, _id, id_post, user, content, date):
        self._id = _id
        self.id_post = id_post
        self.user = user
        self.content = content
        self.date = date

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import os
from dotenv import load_dotenv


load_dotenv()

def create_app():

    # App initialization
    app = Flask(__name__)
    app.config.from_object(os.environ['APP_SETTINGS'])
    app.config['SECRET_KEY'] = os.environ['SECRET_KEY']
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ['DATABASE_URI']
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    with app.app_context():
        app.db = SQLAlchemy()
        app.db.init_app(app)

        # Create tables if not exists
        import models
        app.db.create_all()
        app.db.session.commit()

        # Register blueprints
        from routes import routes
        app.register_blueprint(routes)

        if __name__ == '__main__':
            create_app().run()

        return app

routes.py
from flask import render_template, request, redirect, url_for
from flask import Blueprint

from twitter import Twitter
from db import Database

from datetime import datetime
import os


routes = Blueprint('routes', __name__)

@routes.route("/")
def home():

    # Database posts
    db_posts = Database.get_posts()

    # Remove old posts
    for post in db_posts:
        past_days = (datetime.now() - post.date).days
        if past_days > int(os.environ['DAYS_TO_HOLD_DATA']):
            Database.delete_post_comments(post._id)
            Database.delete_post(post._id)
            db_posts.remove(post)

    # Tweets
    screen_names = ["interinvest", "rafabevilacqua2", "dinheirosabr"]
    contents = [db_post.content for db_post in db_posts]

    for screen_name in screen_names:
        for status in Twitter.user_timeline(screen_name):
            content = status.text
            date = status.created_at

            # Add new Tweets
            past_days = (datetime.now() - date).days
            if past_days < int(os.environ['DAYS_TO_HOLD_DATA']):
                if content not in contents:
                    user = status.user.name
                    Database.add_post(user, content, date)

    return render_template("blog.html", posts=db_posts)

@routes.route("/chat/<post_id>", methods=["GET", "POST"])
def chat(post_id):

    if request.method == "POST":
        Database.add_comment(post_id, request.form.get('comment'))
        return redirect(url_for('routes.chat', post_id=post_id))

    post = Database.get_post(post_id)
    comments = Database.get_post_comments(post_id)

    return render_template("chat.html", post=post, comments=comments)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Top Trades</title>
</head>
<body>
    <header>
        {% block header %}
        {% endblock %}
    </header>
    <section>
        {% block content %}
        {% endblock %}
    </section>
    <footer>
        {% block footer %}
        {% endblock %}
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

templates/blog.html
{% extends "base.html" %}

{% block content %}
    <h1 class="text-center">Tweets da Semana</h1>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Seja bem vindo!</strong> Encontre e interaja com seus Tweets preferidos.
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

    {% for post in posts %}
        <div class="card text-light border-secondary bg-dark mb-3 w-50 mx-auto" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ post.user }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ post.date }}</h6>
                <p class="card-text">{{ post.content }}</p>
            </div>

            <button type="button" class="btn btn-default position-relative mx-auto" aria-label="Left Align">
                <a class="btn btn-dark" href="{{ url_for('routes.chat', post_id=post._id) }}" role="button">
                    <img src="/static/add_icon.png" alt="Comments" width="5%">
                </a>
            </button>
        </div>
    {% endfor %}
    
{% endblock %}

templates/chat.html
{% extends "base.html" %}

{% block header %}
    <button class="btn position-fixed mt-3 end-0 translate-middle bg-warning">
        <a href="{{ url_for('routes.home') }}" role="button">
            <i class="fa fa-home"></i> Tweets da Semana
        </a>
    </button>
{% endblock %}

{% block content %}
    <h1 class="text-center">Discussão Tweet</h1>

    <div class="card text-light border-secondary bg-dark mb-3 w-50 mx-auto" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{post.user}}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{post.date}}</h6>
            <p class="card-text">{{post.content}}</p>
        </div>
    </div>

    {% for comment in comments %}
        <div class="card text-light border-warning mb-3 w-50 mx-auto" style="width: 18rem; background-color:black;">
            <div class="card-body">
                <h5 class="card-title">{{comment.user}}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{comment.date}}</h6>
                <p class="card-text">{{comment.content}}</p>
            </div>
        </div>
    {% endfor %}
    
{% endblock %}

{% block footer %}
<form method="POST">
    <div class="form-group mb-3 mt-5 w-50 mx-auto">
        <label for="comment" class="form-label text-white text-uppercase font-weight-bold">Novo Comentário</label>
        <textarea class="form-control" name="comment" id="comment" rows="4" maxlength=280></textarea>
        <div id="textareaHelp" class="form-text">Nenhum conteúdo será publicado no Twitter.</div>
        <input type="submit" value="Adicionar" class="btn btn-primary btn-lg mb-5 mt-3">
    </div>
</form>
{% endblock %}